[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run react-start"
  targetPort = 3000
  port = 8888
  autoLaunch = true

[[redirects]]
  from = "/api/gemini"
  to = "/.netlify/functions/gemini"
  status = 200
